CREATE TABLE INSURANCES(
ID INT not NULL PRIMARY KEY,
CUSTOMER_ID INT not null,
CAR_ID INT not null,
CREATION_DT  DATETIME,
UPDATED_AT DATETIME,
IS_ACTIVE BOOLEAN,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID),
FOREIGN KEY (CAR_ID) REFERENCES CARS(ID)
);
