CREATE TABLE CAR_DRIVERS(
ID INT not NULL PRIMARY KEY,
DRIVER_ID INT not null,
CAR_ID INT not null,
IS_MAIN_DRIVER BOOLEAN,
FOREIGN key (DRIVER_ID) REFERENCES DRIVERS(ID),
FOREIGN key (CAR_ID) REFERENCES CARS(ID)
);